# Generated by Django 4.1.3 on 2022-12-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFamilia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='dni',
            field=models.IntegerField(max_length=11),
        ),
    ]
