# Generated by Django 4.1.3 on 2022-12-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFamilia', '0002_alter_familiar_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
